/*
This program simulates an entire basketball season for an entire conference. You
click the play button and it will simulate the entire season, and then print out 
the results. You can click reset to reset the data and run the program agian. Click 
Quit to exit. 
*/

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Random;


/**
 *
 * @author Kory Hutchison Section 1
 */
public class March_Madness extends javax.swing.JFrame {

    /**
     * Creates new form March_Madness
     */
    public March_Madness() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ltConference = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ltNonConference = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblTeamName1 = new javax.swing.JLabel();
        lblTeamName2 = new javax.swing.JLabel();
        lblTeamName3 = new javax.swing.JLabel();
        lblTeamName4 = new javax.swing.JLabel();
        lblTeamName5 = new javax.swing.JLabel();
        lblTeamName6 = new javax.swing.JLabel();
        lblTeamName7 = new javax.swing.JLabel();
        lblTeamName8 = new javax.swing.JLabel();
        lblTeamName9 = new javax.swing.JLabel();
        lblTeamName10 = new javax.swing.JLabel();
        lblWins1 = new javax.swing.JLabel();
        lblWins2 = new javax.swing.JLabel();
        lblWins3 = new javax.swing.JLabel();
        lblWins4 = new javax.swing.JLabel();
        lblWins5 = new javax.swing.JLabel();
        lblWins6 = new javax.swing.JLabel();
        lblWins7 = new javax.swing.JLabel();
        lblWins8 = new javax.swing.JLabel();
        lblWins9 = new javax.swing.JLabel();
        lblWins10 = new javax.swing.JLabel();
        lblLosses1 = new javax.swing.JLabel();
        lblLosses2 = new javax.swing.JLabel();
        lblLosses3 = new javax.swing.JLabel();
        lblLosses4 = new javax.swing.JLabel();
        lblLosses5 = new javax.swing.JLabel();
        lblLosses6 = new javax.swing.JLabel();
        lblLosses7 = new javax.swing.JLabel();
        lblLosses8 = new javax.swing.JLabel();
        lblLosses9 = new javax.swing.JLabel();
        lblLosses10 = new javax.swing.JLabel();
        lblStatus1 = new javax.swing.JLabel();
        lblStatus2 = new javax.swing.JLabel();
        lblStatus3 = new javax.swing.JLabel();
        lblStatus4 = new javax.swing.JLabel();
        lblStatus5 = new javax.swing.JLabel();
        lblStatus6 = new javax.swing.JLabel();
        lblStatus7 = new javax.swing.JLabel();
        lblStatus8 = new javax.swing.JLabel();
        lblStatus9 = new javax.swing.JLabel();
        lblStatus10 = new javax.swing.JLabel();
        btnPlay = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();
        cbFivePoints = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("March Madness");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("Conference Teams");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        ltConference.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "BYU", "Gonzaga", "Loyola", "St. Mary's", "Pepperdine", "San Francisco", "San Diego", "Portland", "Pacific", "Santa Clara" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ltConference.setVisibleRowCount(10);
        jScrollPane1.setViewportView(ltConference);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 130, 200));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 250));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setText("Non-Conference Teams");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        ltNonConference.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Arizona", "Florida", "Memphis", "Stanford", "Dayton", "Texas" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(ltNonConference);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 130, 130));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 180, 180));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 3, 10)); // NOI18N
        jLabel3.setText("Status");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setText("Record");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 3, 10)); // NOI18N
        jLabel5.setText("Wins");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 3, 10)); // NOI18N
        jLabel6.setText("Losses");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        lblTeamName1.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblTeamName1.setText(" ");
        jPanel3.add(lblTeamName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        lblTeamName2.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblTeamName2.setText(" ");
        jPanel3.add(lblTeamName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        lblTeamName3.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblTeamName3.setText(" ");
        jPanel3.add(lblTeamName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        lblTeamName4.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblTeamName4.setText(" ");
        jPanel3.add(lblTeamName4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        lblTeamName5.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblTeamName5.setText(" ");
        jPanel3.add(lblTeamName5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        lblTeamName6.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblTeamName6.setText(" ");
        jPanel3.add(lblTeamName6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        lblTeamName7.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblTeamName7.setText(" ");
        jPanel3.add(lblTeamName7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        lblTeamName8.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblTeamName8.setText(" ");
        jPanel3.add(lblTeamName8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        lblTeamName9.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblTeamName9.setText(" ");
        jPanel3.add(lblTeamName9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        lblTeamName10.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblTeamName10.setText(" ");
        jPanel3.add(lblTeamName10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        lblWins1.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblWins1.setText(" ");
        jPanel3.add(lblWins1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, -1));

        lblWins2.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblWins2.setText(" ");
        jPanel3.add(lblWins2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        lblWins3.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblWins3.setText(" ");
        jPanel3.add(lblWins3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));

        lblWins4.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblWins4.setText(" ");
        jPanel3.add(lblWins4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        lblWins5.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblWins5.setText(" ");
        jPanel3.add(lblWins5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        lblWins6.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblWins6.setText(" ");
        jPanel3.add(lblWins6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        lblWins7.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblWins7.setText(" ");
        jPanel3.add(lblWins7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        lblWins8.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblWins8.setText(" ");
        jPanel3.add(lblWins8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, -1));

        lblWins9.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblWins9.setText(" ");
        jPanel3.add(lblWins9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

        lblWins10.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblWins10.setText(" ");
        jPanel3.add(lblWins10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, -1));

        lblLosses1.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblLosses1.setText(" ");
        jPanel3.add(lblLosses1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

        lblLosses2.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblLosses2.setText(" ");
        jPanel3.add(lblLosses2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));

        lblLosses3.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblLosses3.setText(" ");
        jPanel3.add(lblLosses3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));

        lblLosses4.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblLosses4.setText(" ");
        jPanel3.add(lblLosses4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        lblLosses5.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblLosses5.setText(" ");
        jPanel3.add(lblLosses5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, -1));

        lblLosses6.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblLosses6.setText(" ");
        jPanel3.add(lblLosses6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        lblLosses7.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblLosses7.setText(" ");
        jPanel3.add(lblLosses7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, -1));

        lblLosses8.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblLosses8.setText(" ");
        jPanel3.add(lblLosses8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, -1));

        lblLosses9.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblLosses9.setText(" ");
        jPanel3.add(lblLosses9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));

        lblLosses10.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblLosses10.setText(" ");
        jPanel3.add(lblLosses10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, -1, -1));

        lblStatus1.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblStatus1.setText(" ");
        jPanel3.add(lblStatus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, -1));

        lblStatus2.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblStatus2.setText(" ");
        jPanel3.add(lblStatus2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        lblStatus3.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblStatus3.setText(" ");
        jPanel3.add(lblStatus3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));

        lblStatus4.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblStatus4.setText(" ");
        jPanel3.add(lblStatus4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, -1, -1));

        lblStatus5.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblStatus5.setText(" ");
        jPanel3.add(lblStatus5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, -1, -1));

        lblStatus6.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblStatus6.setText(" ");
        jPanel3.add(lblStatus6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        lblStatus7.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblStatus7.setText(" ");
        jPanel3.add(lblStatus7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, -1, -1));

        lblStatus8.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblStatus8.setText(" ");
        jPanel3.add(lblStatus8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));

        lblStatus9.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblStatus9.setText(" ");
        jPanel3.add(lblStatus9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, -1, -1));

        lblStatus10.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblStatus10.setText(" ");
        jPanel3.add(lblStatus10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 480, 300));

        btnPlay.setText("Play");
        btnPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlayMouseClicked(evt);
            }
        });
        getContentPane().add(btnPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, -1, -1));

        btnReset.setText("Reset");
        btnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetMouseClicked(evt);
            }
        });
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, -1, -1));

        btnQuit.setText("Quit");
        btnQuit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuitMouseClicked(evt);
            }
        });
        getContentPane().add(btnQuit, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 350, -1, -1));

        cbFivePoints.setText("Home team 5+");
        getContentPane().add(cbFivePoints, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnQuitMouseClicked

    private void btnPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayMouseClicked
        //Declare Variables and ArrayLists
        int iHomeTeamScore;
        int iVisitingTeamScore;
        int iFivePoints;
        Random rndGenerator = new Random();
        ArrayList<BasketballTeam> Teams = new ArrayList<>();
        ArrayList<BasketballTeam> NonTeams = new ArrayList<>();
        
        //This determines if the 5 points should be added to the home team.
        if(cbFivePoints.isSelected())
        {
            iFivePoints = 5;
        }
        else
        {
            iFivePoints = 0;
        }
        
        //This loads up the names for the Conference teams
        for(int x = 0; x < ltConference.getModel().getSize(); x++)
        {
            ltConference.setSelectedIndex(x);
            Teams.add(new BasketballTeam(ltConference.getSelectedValue()));
        }
        
        //This loads up the names for the Non-Conference teams
        for(int x = 0; x < ltNonConference.getModel().getSize(); x++)
        {
            ltNonConference.setSelectedIndex(x);
            NonTeams.add(new BasketballTeam(ltNonConference.getSelectedValue()));
        }

        //This is the main simulator loop, it takes the first position of the team array,
        //and then teams them up against each team, and goes down the list. It will team
        //up each of those teams against the teams below it in the Array.
        for(int iCount = 0; iCount < Teams.size(); iCount++)
        {
            //This is the loop that controlls all the games.
            for(int iCount2 = iCount + 1; iCount2 < Teams.size(); iCount2++)
            {
                //This loop is for the 2 games between each team. 
                for(int iCount3 = 0; iCount3 < 2; iCount3++)
                {
                    //This loop calculates the scores, and checks to see if there is 
                    //a tie, and it will keep going until there isn't a tie. 
                    do
                    {
                     iHomeTeamScore = rndGenerator.nextInt(100);
                     iVisitingTeamScore = rndGenerator.nextInt(100);
                     iHomeTeamScore = iHomeTeamScore + iFivePoints;   
                    }while(iHomeTeamScore == iVisitingTeamScore);
                    
                    //This if statement is for the first game and gives the home
                    //points to the first team. 
                    if(iCount3 == 0)
                    {
                        if(iHomeTeamScore > iVisitingTeamScore)
                        {
                            Teams.get(iCount).addWins();
                            Teams.get(iCount2).addLosses();
                        }
                        else
                        {
                            Teams.get(iCount).addLosses();
                            Teams.get(iCount2).addWins();
                        }
                    }
                    //This if statement is for the second game and gives the home
                    //points to the second team.
                    else if(iCount3 == 1)
                    {
                        if(iHomeTeamScore > iVisitingTeamScore)
                        {
                            Teams.get(iCount2).addWins();
                            Teams.get(iCount).addLosses();
                        }
                        else
                        {
                            Teams.get(iCount2).addLosses();
                            Teams.get(iCount).addWins();
                        }
                    }
                
                }   
                
            }
        }
        
        //This for loop simulates all the games against the Non Conference teams
        for(int iCount = 0; iCount < Teams.size(); iCount++)
        {
            //This does each game with all the Non Conference teams. 
            for(int iCount2 = 0; iCount2 < NonTeams.size(); iCount2++)
            {
                do
                {
                    iHomeTeamScore = rndGenerator.nextInt(100);
                    iVisitingTeamScore = rndGenerator.nextInt(100);   
                }while(iHomeTeamScore == iVisitingTeamScore);
                
                if(iHomeTeamScore > iVisitingTeamScore)
                {
                    Teams.get(iCount).addWins();
                    NonTeams.get(iCount2).addLosses();
                }
                else
                {
                    Teams.get(iCount).addLosses();
                    NonTeams.get(iCount2).addWins();
                }
            }
        }
        
        //This sorts the array
        Collections.sort(Teams, new Comparator<BasketballTeam>()
        {
            public int compare(BasketballTeam b1, BasketballTeam b2)
            {
                return Integer.valueOf(b2.getWins()).compareTo(b1.getWins());
            }
        });
        
        //This loop goes through and determines the status of the team depending on their record.
        for(int iCount = 0; iCount < Teams.size(); iCount++)
        {
            if(Teams.get(iCount).getWins() >= 18)
            {
                Teams.get(iCount).setStatus("March Madness");
            }
            else if(Teams.get(iCount).getWins() >= 15)
            {
                Teams.get(iCount).setStatus("NIT");
            }
            else
            {
                Teams.get(iCount).setStatus("See you next year");
            }
        }
        
        //These statements set the labels for the output.
        lblTeamName1.setText(Teams.get(0).getTeamName());
        lblWins1.setText(String.valueOf(Teams.get(0).getWins()));
        lblLosses1.setText(String.valueOf(Teams.get(0).getLosses()));
        lblStatus1.setText(Teams.get(0).getStatus());
        
        lblTeamName2.setText(Teams.get(1).getTeamName());
        lblWins2.setText(String.valueOf(Teams.get(1).getWins()));
        lblLosses2.setText(String.valueOf(Teams.get(1).getLosses()));
        lblStatus2.setText(Teams.get(1).getStatus());
        
        lblTeamName3.setText(Teams.get(2).getTeamName());
        lblWins3.setText(String.valueOf(Teams.get(2).getWins()));
        lblLosses3.setText(String.valueOf(Teams.get(2).getLosses()));
        lblStatus3.setText(Teams.get(2).getStatus());
        
        lblTeamName4.setText(Teams.get(3).getTeamName());
        lblWins4.setText(String.valueOf(Teams.get(3).getWins()));
        lblLosses4.setText(String.valueOf(Teams.get(3).getLosses()));
        lblStatus4.setText(Teams.get(3).getStatus());
        
        lblTeamName5.setText(Teams.get(4).getTeamName());
        lblWins5.setText(String.valueOf(Teams.get(4).getWins()));
        lblLosses5.setText(String.valueOf(Teams.get(4).getLosses()));
        lblStatus5.setText(Teams.get(4).getStatus());
        
        lblTeamName6.setText(Teams.get(5).getTeamName());
        lblWins6.setText(String.valueOf(Teams.get(5).getWins()));
        lblLosses6.setText(String.valueOf(Teams.get(5).getLosses()));
        lblStatus6.setText(Teams.get(5).getStatus());
        
        lblTeamName7.setText(Teams.get(6).getTeamName());
        lblWins7.setText(String.valueOf(Teams.get(6).getWins()));
        lblLosses7.setText(String.valueOf(Teams.get(6).getLosses()));
        lblStatus7.setText(Teams.get(6).getStatus());
        
        lblTeamName8.setText(Teams.get(7).getTeamName());
        lblWins8.setText(String.valueOf(Teams.get(7).getWins()));
        lblLosses8.setText(String.valueOf(Teams.get(7).getLosses()));
        lblStatus8.setText(Teams.get(7).getStatus());
        
        lblTeamName9.setText(Teams.get(8).getTeamName());
        lblWins9.setText(String.valueOf(Teams.get(8).getWins()));
        lblLosses9.setText(String.valueOf(Teams.get(8).getLosses()));
        lblStatus9.setText(Teams.get(8).getStatus());
        
        lblTeamName10.setText(Teams.get(9).getTeamName());
        lblWins10.setText(String.valueOf(Teams.get(9).getWins()));
        lblLosses10.setText(String.valueOf(Teams.get(9).getLosses()));
        lblStatus10.setText(Teams.get(9).getStatus());
   
    }//GEN-LAST:event_btnPlayMouseClicked

    private void btnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseClicked
        //These statements clear all the data in the labels.
        lblTeamName1.setText("");
        lblWins1.setText("");
        lblLosses1.setText("");
        lblStatus1.setText("");
        
        lblTeamName2.setText("");
        lblWins2.setText("");
        lblLosses2.setText("");
        lblStatus2.setText("");
        
        lblTeamName3.setText("");
        lblWins3.setText("");
        lblLosses3.setText("");
        lblStatus3.setText("");
        
        lblTeamName4.setText("");
        lblWins4.setText("");
        lblLosses4.setText("");
        lblStatus4.setText("");
        
        lblTeamName5.setText("");
        lblWins5.setText("");
        lblLosses5.setText("");
        lblStatus5.setText("");
        
        lblTeamName6.setText("");
        lblWins6.setText("");
        lblLosses6.setText("");
        lblStatus6.setText("");
        
        lblTeamName7.setText("");
        lblWins7.setText("");
        lblLosses7.setText("");
        lblStatus7.setText("");
        
        lblTeamName8.setText("");
        lblWins8.setText("");
        lblLosses8.setText("");
        lblStatus8.setText("");
        
        lblTeamName9.setText("");
        lblWins9.setText("");
        lblLosses9.setText("");
        lblStatus9.setText("");
        
        lblTeamName10.setText("");
        lblWins10.setText("");
        lblLosses10.setText("");
        lblStatus10.setText("");
    }//GEN-LAST:event_btnResetMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(March_Madness.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(March_Madness.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(March_Madness.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(March_Madness.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new March_Madness().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnQuit;
    private javax.swing.JButton btnReset;
    private javax.swing.JCheckBox cbFivePoints;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblLosses1;
    private javax.swing.JLabel lblLosses10;
    private javax.swing.JLabel lblLosses2;
    private javax.swing.JLabel lblLosses3;
    private javax.swing.JLabel lblLosses4;
    private javax.swing.JLabel lblLosses5;
    private javax.swing.JLabel lblLosses6;
    private javax.swing.JLabel lblLosses7;
    private javax.swing.JLabel lblLosses8;
    private javax.swing.JLabel lblLosses9;
    private javax.swing.JLabel lblStatus1;
    private javax.swing.JLabel lblStatus10;
    private javax.swing.JLabel lblStatus2;
    private javax.swing.JLabel lblStatus3;
    private javax.swing.JLabel lblStatus4;
    private javax.swing.JLabel lblStatus5;
    private javax.swing.JLabel lblStatus6;
    private javax.swing.JLabel lblStatus7;
    private javax.swing.JLabel lblStatus8;
    private javax.swing.JLabel lblStatus9;
    private javax.swing.JLabel lblTeamName1;
    private javax.swing.JLabel lblTeamName10;
    private javax.swing.JLabel lblTeamName2;
    private javax.swing.JLabel lblTeamName3;
    private javax.swing.JLabel lblTeamName4;
    private javax.swing.JLabel lblTeamName5;
    private javax.swing.JLabel lblTeamName6;
    private javax.swing.JLabel lblTeamName7;
    private javax.swing.JLabel lblTeamName8;
    private javax.swing.JLabel lblTeamName9;
    private javax.swing.JLabel lblWins1;
    private javax.swing.JLabel lblWins10;
    private javax.swing.JLabel lblWins2;
    private javax.swing.JLabel lblWins3;
    private javax.swing.JLabel lblWins4;
    private javax.swing.JLabel lblWins5;
    private javax.swing.JLabel lblWins6;
    private javax.swing.JLabel lblWins7;
    private javax.swing.JLabel lblWins8;
    private javax.swing.JLabel lblWins9;
    private javax.swing.JList<String> ltConference;
    private javax.swing.JList<String> ltNonConference;
    // End of variables declaration//GEN-END:variables
}
